name: Pull Requests

on:
  pull_request:

jobs:
  build:
    name: Build dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        id: jdk-8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        id: build
        run: |
          ./gradlew build
      - name: Archive Test Report
        id: archive-reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: it-test-logs
          retention-days: 7
          path: build/reports/tests/**